/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rudy.ryanto.order.system.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum paymentOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<paymentOrderStatus> {
  COMPLETED, CANCELED, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"paymentOrderStatus\",\"namespace\":\"com.rudy.ryanto.order.system.kafka.order.avro.model\",\"symbols\":[\"COMPLETED\",\"CANCELED\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
